---
version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      UnusedFormalParameter:
        enabled: false
  phpcodesniffer:
    enabled: true
  SonarPHP:
    enabled: true
  phan:
    enabled: true

exclude_patterns:
- "config/"
- "tests/"
